os: linux
dist: focal
arch: ppc64le
group: edge

services:
    - docker
jobs:
  include: 
    - language: node_js
      node_js:
        - 16
      script:
        - sudo apt-get -y -qq install sshpass
