os: linux
dist: focal

services:
    - docker

jobs:
  include: 
    - language: shell
      arch: ppc4le
      os: linux
      dist: focal
      script:
        - docker pull ubuntu:23.04
        - docker images
    - language: shell
      arch: ppc64le   
      os: linux
      dist: focal
      group: edge
      script:
        - cat /usr/local/bin/docker_func
        - docker run quay.io/podman/stable echo "Hello, world!"
        - docker images

        
