os: linux
dist: focal
arch: ppc64le
group: edge

services:
    - docker
jobs:
  include: 
    - language: node_js
      node_js:
        - 16
      script:
        - docker version
        - docker run -d -p 80:80 --name test_docker -v $HOME:/usr nginx
        - docker ps
        - nproc
        - docker inspect --format '{{.HostConfig.CpuShares}}' test_docker
